run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.24"
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
      path: stdout
    - format: junit-xml
      path: report.xml
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/klassmann/cpfcnpj
  
  
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
    ignored-numbers: [0,1,2,3,4,5,6,7,8,9,10,11,14,48,100]
  
  govet:
    enable-all: true
  
  lll:
    line-length: 120
    tab-width: 4
  
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  staticcheck:
    checks: ["all"]
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist:
      - fmt
  
  unused: {}
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*_test.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
    
    - path: utils\.go
      text: "Magic number"
      linters:
        - mnd
    
    - linters:
        - staticcheck
      text: "SA9003:"
    
    - linters:
        - lll
      source: "^//go:generate "
  
  exclude-use-default: false
  exclude-case-sensitive: false
  include:
    - EXC0002
    - EXC0003
    - EXC0004
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
  
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false